---
title: "Experimental Psychology"
subtitle: "PSY 4433/4433A Syllabus"
author: "Jonathan A. Pedroza, PhD"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{css my-header-colors, echo = FALSE}
.page-header {
  color: #FAE9A0;
  text-align: center;
  background-color: #005C55;
  background-image: linear-gradient(120deg, #7DA37B, #005C55);
}

a {
  color: #F1C40F; #color of linked inline code
  font-weight: bold;
  text-decoration: none;
}
  a:hover {
    text-decoration: underline;
    }

.main-content {
  word-wrap: break-word; }
  .main-content :first-child {
    margin-top: 0; }
  @media screen and (min-width: 64em) {
    .main-content {
      max-width: 64rem;
      padding: 2rem 6rem;
      margin: 0 auto;
      font-size: 1.1rem; } }
  @media screen and (min-width: 42em) and (max-width: 64em) {
    .main-content {
      padding: 2rem 4rem;
      font-size: 1.1rem; } }
  @media screen and (max-width: 42em) {
    .main-content {
      padding: 2rem 1rem;
      font-size: 1rem; } }
  .main-content img {
    max-width: 100%; }
  .main-content h1,
  .main-content h2,
  .main-content h3,
  .main-content h4,
  .main-content h5,
  .main-content h6 {
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: normal;
    color: #3F7F68; } # header color
  .main-content p {
    margin-bottom: 1em; }
  .main-content code {
    padding: 2px 4px;
    font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
    font-size: 0.9rem;
    color: #005C55; #package color/whatever is in `` brackets
    background-color: #7DA37B; #background color of ``brackets
    border-radius: 0.3rem; }
  .main-content pre {
    padding: 0.8rem;
    margin-top: 0;
    margin-bottom: 1rem;
    font: 1rem Consolas, "Liberation Mono", Menlo, Courier, monospace;
    color: #567482;
    word-wrap: normal;
    background-color: #f3f6fa; #background color of code chunks
    border: solid 1px #005C55; #this is the border of the r code chunks
    border-radius: 0.3rem; }
    .main-content pre > code {
      padding: 0;
      margin: 0;
      font-size: 0.9rem;
      color: #5D6D7E;
      word-break: normal;
      white-space: pre;
      background: transparent;
      border: 0; }
  .main-content .highlight {
    margin-bottom: 1rem; }
    .main-content .highlight pre {
      margin-bottom: 0;
      word-break: normal; }
  .main-content .highlight pre,
  .main-content pre {
    padding: 0.8rem;
    overflow: auto;
    font-size: 0.9rem;
    line-height: 1.45;
    border-radius: 0.3rem;
    -webkit-overflow-scrolling: touch; }
  .main-content pre code,
  .main-content pre tt {
    display: inline;
    max-width: initial;
    padding: 0;
    margin: 0;
    overflow: initial;
    line-height: inherit;
    word-wrap: normal;
    background-color: transparent;
    border: 0; }
    .main-content pre code:before, .main-content pre code:after,
    .main-content pre tt:before,
    .main-content pre tt:after {
      content: normal; }
  .main-content ul,
  .main-content ol {
    margin-top: 0; }
  .main-content blockquote {
    padding: 0 1rem;
    margin-left: 0;
    color: #819198;
    border-left: 0.3rem solid #dce6f0; }
    .main-content blockquote > :first-child {
      margin-top: 0; }
    .main-content blockquote > :last-child {
      margin-bottom: 0; }
  .main-content table {
    display: block;
    width: 100%;
    overflow: auto;
    word-break: normal;
    word-break: keep-all;
    -webkit-overflow-scrolling: touch; }
    .main-content table th {
      font-weight: bold; }
    .main-content table th,
    .main-content table td {
      padding: 0.5rem 1rem;
      border: 1px solid #e9ebec; }
  .main-content dl {
    padding: 0; }
    .main-content dl dt {
      padding: 0;
      margin-top: 1rem;
      font-size: 1rem;
      font-weight: bold; }
    .main-content dl dd {
      padding: 0;
      margin-bottom: 1rem; }
  .main-content hr {
    height: 2px;
    padding: 0;
    margin: 1rem 0;
    background-color: #5E9171; #line to break up sections
    border: 0;
}
```

## Meeting Time
### Lecture: **M/W 6-7:15pm**
### PSY 4433A-10 Activity: **M 4-5:50pm**
### PSY 4433A-11 Activity: **W 4-5:50pm**

-----------------------------------

## Instructor: Jonathan A. Pedroza, PhD
### Preferred Name: Jon/JP
### Pronouns: he/him/his
### Email: japedroza@cpp.edu

## Office: Virtual
### Office Hours: XX

## Required Materials: Textbook & SPSS
## Optional Materials: APA 7th Edition Manual
## Required Text: [Gravetter, Frederick J. & Forzano, Lori-Ann B. (2018). *Research Methods for the Behavioral Sciences.* (6th Edition) Boston: Cengage Learning ISBN:	9781337613316](https://www.google.com/search?q=research+methods+for+the+behavioral+sciences&rlz=1C1CHBF_enUS926US926&oq=Research+Methods+for+the+Behavioral+Sciences&aqs=chrome.0.35i39j46i512j0i512l6j46i512j0i512.570j0j7&sourceid=chrome&ie=UTF-8)
## SPSS: [CPP Virtual Lab](https://www.cpp.edu/it/virtual-software-lab/index.shtml)
## OneDrive: [OneDrive Recordings](https://livecsupomona-my.sharepoint.com/:f:/g/personal/japedroza_cpp_edu/ErXOwUp0XIxMuVLEmXmoVsUBnurbqUVZUIqNeV9LkGBUpA?e=zdXGDU)

## Corequisites: PSY 4433 & PSY 4433A
## Prerequisites: PSY 2201, PSY 2204, & PSY 3307/3307A

## Zoom Information:

### PSY 4433 Lecture: https://cpp.zoom.us/j/83501705321
### Meeting ID: 835 0170 5321

### PSY 4433A-10: https://cpp.zoom.us/j/86593597665
### Meeting ID: 865 9359 7665

### PSY 4433A-11: https://cpp.zoom.us/j/83597827008
### Meeting ID: 835 9782 7008

-----------------------------------

# Course Description

This course is designed to further your knowledge on correlational and experimental research designs with an emphasis on **experimental designs**. Students will learn aspects of advanced research designs including how to design and conduct an experimental from coming up with a research idea to completing a research/project paper. Students will also learn to critically evaluate research.  

-----------------------------------

# Course Structure

XX

-----------------------------------

# Course Objectives

XX

-----------------------------------

# Grading Policy

**Overview**

XX

```{r}

```

-----------------------------------

# Assignments

XX

-----------------------------------

# Other Policies

## **Academic Integrity:** 
Students are expected to adhere to the University’s Student Conduct Code (https://www.cpp.edu/studentconduct/student-conduct-code.shtml). Academic integrity violations, including, but not limited to, cheating and plagiarism, may result in a 0 for an assignment or exam and will be reported to the Office of Student Conduct & Integrity.

## **Accommodations:** 
Reasonable accommodations will be provided for students with learning, physical, or other disabilities. Accommodations approved through the Disability Resource Center (909-869-3333) should be discussed with the instructor early in the semester to ensure appropriate implementation. 

## **Distribution of Course Materials:** 
Do not copy/screenshot or retain any exam questions. Violation of this policy is grounds for disciplinary action. Distribution of other course materials, including slides, video lectures, SPSS assignments, and problem sets/quizzes, is allowable. 

## **Mandatory Reporting:**
Please note two executive orders from the CSU’s Office of the Chancellor that limit what information faculty members can keep confidential. **Executive Order 1083 relates to reporting of child abuse** and **Executive Order 1096 relates to reporting of campus sexual assaults**. CSU faculty members are considered mandatory reporters. Once we are made aware of such incidents, we are required to report the incident to our Title IX officer on campus, regardless of whether the student wants the information reported.

## **Student Health & Well-being:**
Students experiencing emotional distress may seek services through [Counseling & Psychological Services](https://www.cpp.edu/caps/index.shtml). Additionally, there is the [Student Health & Wellbeing](https://www.cpp.edu/health/student-health-services.shtml) for other health issues. 

-----------------------------------

# Still in the Pandemic

## Cameras
If you feel comfortable please turn on your camera. However, I understand that you may be in a situation where you may not be able to have your camera on. I would like to see your faces, simply because I want to gauge understanding. This is much easier by seeing the looks on your faces.

## Participation
Please interrupt at any time if you do not understand anything...and I mean ANYTHING. This class includes the essentials for a lot of research and practical applications in both the social and biological sciences. It is important to understand as much as possible regarding the statistical tests that we will learn during this semester. Communication is key for this class. I will also offer office hours to discuss class assignments. **Please email me if the office hours do not work for you.**

## Pandemic-related Accomodations
We are still in a pandemic so please communicate with me if you are not able to meet the requirements of this class. While no late assignments will be accepted, accommodations due to pandemic-related issues will be honored. If there is no prior communication about not being able to meet the requirements for an assignment, a zero for that assignment will be assigned. 

## Classes Will Be Recorded
All classes will be recorded with automated closed captions and a full automated transcription of each lecture. Please email me if you have any concerns regarding the lecture being recorded to see if there are any accomodations that can be made.

-----------------------------------
